(()=>{
  const COVERAGE_VERSION='2026-09-15.1';
  const order=['Elba','Sardegna','Toscana','Corsica'];
  let installed=false;
  function activeStructures(){return (typeof structures!=='undefined'?structures:[]).filter(r=>r.napoleon_active&&r.live_napoleon_status==='live')}
  function isCovered(r){return r.has_internal_2027===true||r.source_coverage_status==='PRESENTE'}
  function e(v){return typeof esc==='function'?esc(v):(v==null?'—':String(v))}
  function ensureStyle(){if(document.getElementById('coverageStyleV1'))return;const s=document.createElement('style');s.id='coverageStyleV1';s.textContent=`.cov-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:8px;margin-bottom:10px}.cov-kpi{background:#fff;border:1px solid var(--ln);border-radius:9px;padding:10px}.cov-kpi small{display:block;color:var(--mu);font-size:10px;font-weight:800;text-transform:uppercase}.cov-kpi b{font-size:20px}.cov-kpi span{display:block;font-size:10px;color:var(--mu);margin-top:3px}.cov-toolbar{background:#fff;border:1px solid var(--ln);border-radius:9px;padding:9px;display:flex;gap:7px;align-items:end;flex-wrap:wrap;margin-bottom:9px}.cov-toolbar .field{min-width:155px}.cov-toolbar .search{flex:1;min-width:220px}.cov-present td{background:#eefaf3}.cov-missing td{background:#fff2f2}.cov-status{font-weight:900}.cov-present .cov-status{color:#18704a}.cov-missing .cov-status{color:#a73030}.cov-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px;vertical-align:0}.cov-present .cov-dot{background:#18704a}.cov-missing .cov-dot{background:#a73030}.cov-muted{font-size:10px;color:#667085}.cov-count{margin-left:auto;color:#667085;font-size:11px;padding:8px}@media(max-width:1000px){.cov-summary{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
  function install(){ensureStyle();const tab=document.querySelector('.tab[data-p="coverage"]');if(tab)tab.textContent='Copertura USO INTERNO';const panel=document.getElementById('p-coverage');if(!panel)return;panel.innerHTML=`<div class="card"><b>Copertura USO INTERNO 2027</b><p>Elenco completo delle strutture Napoleon attive. Verde = USO INTERNO presente; rosso = mancante. Vista di sola consultazione.</p></div><div id="covSummary" class="cov-summary"></div><div class="cov-toolbar"><div class="field search"><label>Cerca struttura</label><input id="covQ" placeholder="Nome o località"></div><div class="field"><label>Catalogo</label><select id="covDest"><option value="">Tutti</option><option>Elba</option><option>Sardegna</option><option>Toscana</option><option>Corsica</option></select></div><div class="field"><label>USO INTERNO</label><select id="covStatus"><option value="">Tutti</option><option value="present">Presenti</option><option value="missing">Mancanti</option></select></div><div class="cov-count"><b id="covVisible">0</b> strutture</div></div><div class="wrap"><table style="table-layout:auto"><thead><tr><th>Catalogo</th><th>Struttura</th><th>Località</th><th>USO INTERNO 2027</th></tr></thead><tbody id="covBody"></tbody></table></div><div class="cov-muted" style="margin-top:8px">Dati sincronizzati con l'anagrafica master dell'audit · ${COVERAGE_VERSION}</div>`;['covQ','covDest','covStatus'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='covQ'?'input':'change',renderCoverage)});installed=true;renderCoverage()}
  function renderSummary(rows){const summary=document.getElementById('covSummary');if(!summary)return;const totals={};order.forEach(d=>totals[d]={active:0,covered:0});rows.forEach(r=>{if(!totals[r.destination])totals[r.destination]={active:0,covered:0};totals[r.destination].active++;if(isCovered(r))totals[r.destination].covered++});const active=rows.length,covered=rows.filter(isCovered).length;const card=(label,c,a)=>`<div class="cov-kpi"><small>${e(label)}</small><b>${c}/${a}</b><span>${a-c} mancanti</span></div>`;summary.innerHTML=card('Totale',covered,active)+order.map(d=>card(d,totals[d]?.covered||0,totals[d]?.active||0)).join('')}
  function renderCoverage(){if(!installed){install();return}const all=activeStructures();renderSummary(all);const q=(document.getElementById('covQ')?.value||'').trim().toLowerCase(),dest=document.getElementById('covDest')?.value||'',st=document.getElementById('covStatus')?.value||'',sortIndex=new Map(order.map((d,i)=>[d,i]));const rr=all.filter(r=>{const present=isCovered(r),text=((r.canonical_name||'')+' '+(r.locality||'')).toLowerCase();return(!dest||r.destination===dest)&&(!st||(st==='present'?present:!present))&&(!q||text.includes(q))}).sort((a,b)=>(sortIndex.get(a.destination)??99)-(sortIndex.get(b.destination)??99)||String(a.canonical_name).localeCompare(String(b.canonical_name),'it'));const body=document.getElementById('covBody');if(body)body.innerHTML=rr.map(r=>{const present=isCovered(r);return`<tr class="${present?'cov-present':'cov-missing'}"><td><b>${e(r.destination)}</b></td><td><b>${e(r.canonical_name)}</b></td><td>${e(r.locality)}</td><td class="cov-status"><span class="cov-dot"></span>${present?'PRESENTE':'MANCANTE'}</td></tr>`}).join('');const n=document.getElementById('covVisible');if(n)n.textContent=rr.length}
  function hook(){if(typeof render==='function'&&!render.__coverageHook){const old=render,wrapped=function(){const x=old.apply(this,arguments);renderCoverage();return x};wrapped.__coverageHook=true;render=wrapped}if(typeof renderStructures==='function'&&!renderStructures.__coverageHook){const old=renderStructures,wrapped=function(){const x=old.apply(this,arguments);renderCoverage();return x};wrapped.__coverageHook=true;renderStructures=wrapped}}
  hook();install();setTimeout(()=>{hook();renderCoverage()},300)
})();
